---
all:
  children:
    development:
      hosts:
        lenovo:
          ansible_host: ssh.vibir.lt
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ubuntu:
      hosts:
        lenovo:
          ansible_host: ssh.vibir.lt
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
